// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import dotenv from "dotenv";
import { defineConfig } from "prisma/config";

// Match Next.js's own env-file precedence (.env.local overrides .env) so the
// Prisma CLI (migrate/seed) sees the same DATABASE_URL the app itself uses,
// instead of only ever reading the placeholder committed in .env.
dotenv.config();
dotenv.config({ path: ".env.local", override: true });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
